repos:
  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.0  # Use the latest version
    hooks:
      - id: ruff
        args: [--fix]
      - id: ruff-format

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
      - id: check-added-large-files
      - id: check-toml
      - id: debug-statements

  -   repo: https://github.com/python-poetry/poetry
      rev: '1.8.4'
      hooks:
        -   id: poetry-check
        -   id: poetry-lock
        -   id: poetry-export
        -   id: poetry-install
