sources:
  - name: Dune1
    type: dune
    key: ${DUNE_API_KEY}
  - name: PG1
    type: postgres
    key: ${DB_URL}

destinations:
  - name: Dune1
    type: dune
    key: ${DUNE_API_KEY}
  - name: PG1
    type: postgres
    key: ${DB_URL}

jobs:
  - name: Sync Parameterized Dune Query with Multiple Types to Postgres
    source:
      ref: Dune1
      query_id: 4238114
      query_engine: medium
      poll_frequency: 5
      parameters:
        - name: blockchain
          value: gnosis
          type: ENUM
        - name: blocktime
          value: "2024-09-01 00:00:00"
          type: DATE
        - name: result_limit
          value: "10"
          type: NUMBER
    destination:
      ref: PG1
      table_name: results_4238114
      if_exists: replace

  - name: Table Independent Query to Dune
    source:
      ref: PG1
      if_exists: append
      query_string: "SELECT 1 as number, '\\x1234'::bytea as my_bytes;"
    destination:
      ref: Dune1
      table_name: dune_sync_test_table
