# The ID of the query to execute
query_id = 4159712
# The name of the table where the query results will be stored
table_name = "results_table"
# The frequency (in seconds) at which the query should be polled
poll_frequency = 2
# The query engine to use (valid values are "medium" or "large")
query_engine = "medium"