data_sources:
  - name: Dune
    type: dune
    key: ${DUNE_API_KEY}
  - name: PG
    type: postgres
    key: ${DB_URL}

jobs:
  - name: d2p-test-1
    source:
      ref: Dune
      query_id: 4238114
      query_engine: medium
      poll_frequency: 5
      parameters:
        - name: blockchain
          value: gnosis
          type: ENUM
        - name: blocktime
          value: "2024-09-01 00:00:00"
          type: DATE
        - name: result_limit
          value: "10"
          type: NUMBER
    destination:
      ref: PG
      table_name: results_4238114
      if_exists: upsert
      index_columns:
        - hash

  - name: p2d-test
    source:
      ref: PG
      query_string: "SELECT 1 as number, '\\x1234'::bytea as my_bytes;"
    destination:
      ref: Dune
      table_name: dune_sync_test_table

  - name: cow-solvers
    source:
      ref: Dune
      query_id: 4345829
      query_engine: medium
      poll_frequency: 3
    destination:
      ref: PG
      table_name: cow.solvers
      if_exists: replace
