[[jobs]]
# Job 1 configuration
query_id = 4159712
table_name = "results_table_1"
poll_frequency = 2
query_engine = "medium"

[[jobs]]
# Job 2 configuration
query_id = 4159713
table_name = "results_table_2"
poll_frequency = 5
query_engine = "large"

[[jobs]]
# Job 3 configuration
query_id = 4159714
table_name = "results_table_3"
poll_frequency = 10
query_engine = "medium"