sources:
  - name: Dune
    type: dune
    key: ${DUNE_API_KEY}
  - name: PG
    type: postgres
    key: ${READONLY_DB}

destinations:
  - name: Dune
    type: dune
    key: ${DUNE_API_KEY}
  - name: PG
    type: postgres
    key: ${DB_URL}

jobs:
  # - name: Dune2Pg
  #   source:
  #     ref: Dune
  #     query_id: 4232873
  #     query_engine: medium
  #     poll_frequency: 5
  #     parameters:
  #       - name: blockchain
  #         value: ethereum
  #         type: TEXT
  #   destination:
  #     ref: PG
  #     table_name: results_4232873
  #     if_exists: replace

  - name: Pg2Dune
    source:
      ref: PG
      query_string: "select * from orders order by creation_timestamp desc limit 1"
    destination:
      ref: Dune
      table_name: dune_sync_test_felix

  # - name: Sync Parameterized Dune Query with Multiple Types to Postgres
  #   source:
  #     ref: Dune
  #     query_id: 4273244
  #     query_engine: medium
  #     poll_frequency: 5
  #   destination:
  #     ref: PG
  #     table_name: app_data
  #     if_exists: replace
