[[jobs]]
source = "dune"
destination = "postgres"
query_id = 4159712
table_name = "results_4159712"
poll_frequency = 2
query_engine = "medium"
if_exists = "append"

[[jobs]]
source = "dune"
destination = "postgres"
query_id = 4238114
table_name = "parameterized_results_4238114"
poll_frequency = 2
query_engine = "medium"
if_exists = "replace"

[[jobs.query_parameters]]
name = "blockchain"
type = "ENUM"
value = "gnosis"

[[jobs.query_parameters]]
name = "block_time"
type = "DATE"
value = "2024-09-01 00:00:00"

[[jobs.query_parameters]]
name = "result_limit"
type = "NUMBER"
value = "10"

[[jobs]]
source = "postgres"
destination = "dune"
table_name = "dune_destination_table"
query_string = "SELECT * FROM parameterized_results_4238114"

# hoomoos test job FROM POSTGRES
#[[jobs]]
#source = "postgres"
#destination = "dune"
#table_name = "some_dummy_table_again"
#query_string = "SELECT * FROM results_4194034"

# hoomoos test job FROM DUNE
#[[jobs]]
#source = "dune"
#destination = "postgres"
#table_name = "results_4194034"
#query_id = 4194034
#poll_frequency = 5
#query_engine = "medium"
