name: End to End Test
on: push

jobs:
  db-job:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_PASSWORD: postgres
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432
        # Copy repo contents into container (needed to populate DB)
        volumes:
          - ${{ github.workspace }}:/repo
    steps:
      - uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - name: Install Requirements
        run: pip install -r requirements/dev.txt
      - name: Tests
        run: python -m pytest tests/e2e.py
        # Environment variables used by the `pg_client.py`
        env:
          POSTGRES_HOST: localhost
          POSTGRES_PORT: 5432
